# Generated by Django 5.2.4 on 2025-07-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videoprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
